### ISSUE TITLE
gelf optionnal

### ISSUE THREAD

**Issue by notFloran** [Hexanet/MonologExtraBundle#1]
TODO : 
- [ ] suggest **graylog2/gelf-php** instead of required
- [ ] Add option to enable Gelf publisher 
- [ ] Check that  **graylog2/gelf-php** exist when gelf publisher is enabled

**Comment by notFloran** [comment]
See https://github.com/bzikarsky/gelf-php/issues/56 for errors

**Comment by notFloran** [comment]
See https://github.com/bzikarsky/gelf-php/issues/56 to replace Publisher

**Comment by notFloran** [comment]
Example : 

``` yaml
services:
    gelf.udp_transport:
        class: Gelf\Transport\UdpTransport
        arguments:
            - "%graylog_host%"
            - "%graylog_port%%"

    gelf.transport:
        class: Gelf\Transport\IgnoreErrorTransportWrapper
        arguments:
            - "@gelf.udp_transport"

    gelf.publisher:
        class: Gelf\Publisher
        arguments:
            - "@gelf.transport"

monolog:
    handlers:
        gelf:
            type: gelf
            publisher: gelf.publisher
            level: debug
```
